// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLhEBGaiHjc4GD6ExPM82XvucT9Oju5BQ',
    appId: '1:194181182615:web:7723c865ccf6f13b6be5d2',
    messagingSenderId: '194181182615',
    projectId: 'week-07-9ef75',
    authDomain: 'week-07-9ef75.firebaseapp.com',
    storageBucket: 'week-07-9ef75.firebasestorage.app',
    measurementId: 'G-NPL444Q9BY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUJMP78r-EQCB-JZk1H3NdRh3j5n4-fuE',
    appId: '1:194181182615:android:03dd303909a898f06be5d2',
    messagingSenderId: '194181182615',
    projectId: 'week-07-9ef75',
    storageBucket: 'week-07-9ef75.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLhEBGaiHjc4GD6ExPM82XvucT9Oju5BQ',
    appId: '1:194181182615:web:6ca034ecfd7916c06be5d2',
    messagingSenderId: '194181182615',
    projectId: 'week-07-9ef75',
    authDomain: 'week-07-9ef75.firebaseapp.com',
    storageBucket: 'week-07-9ef75.firebasestorage.app',
    measurementId: 'G-JCW780W4VH',
  );
}
